Repository STACK-UP-3/warriorz-backend, pull requests merged in 2020-04, with the labels that each got.

#12 #171784084 add signup feature resources
  .env.example
  .eslintrc.json
  .prettierrc
  .sequelizerc
  logs/all.log.28-03-2020
  logs/error.log.28-03-2020
  package.json
  server/app.js
  server/config/config.js
  server/controllers/usercontroller.js
  server/helpers/util.js
  server/helpers/validateSchema.js
  server/middlewares/notFound.js
  server/middlewares/validators/validate.js
  server/migrations/20200331142748-create-users.js
  server/models/index.js
  server/models/users.js
  server/routes/api/apiRoutes.js
  server/routes/api/users/userRoutes.js
  server/routes/index.js
  server/services/email.create.js
  server/services/templates/verMessage.js
  server/services/userService.js
  server/swagger/index.js
  server/swagger/signup.swagger.js
  server/swagger/test.swagger.js
  server/tests/app.test.js
  server/tests/setup.js
  server/tests/signup.test.js
  server/tests/testData/signup.testData.js
Labels: Ready For Review

#13 #171784083 Setup the API endpoint for user sign-in
  .eslintrc.json
  .gitignore
  package.json
  server/app.js
  server/controllers/usercontroller.js
  server/helpers/validateSchema.js
  server/index.js
  server/middlewares/validators/validate.js
  server/routes/api/users/userRoutes.js
  server/routes/index.js
  server/services/userService.js
  server/swagger/signin.swagger.js
  server/tests/user.signin.test.js
Labels: Ready For Merge, enhancement

#18 #172240251 Fix the Heroku PORT error
  server/index.js
Labels: Ready For Merge, bug

#14 #171784086 Reset Password via email
  package.json
  server/controllers/usercontroller.js
  server/helpers/resetEncode.js
  server/helpers/validateSchema.js
  server/middlewares/validators/validate.js
  server/middlewares/verifications/verifyUser.js
  server/models/index.js
  server/routes/api/apiRoutes.js
  server/routes/api/users/featuresRoute.js
  server/services/email.create.js
  server/swagger/resetPass.swagger.js
  server/swagger/signup.swagger.js
  server/tests/resetpass.test.js
Labels: Ready For Merge, enhancement

#16 #171784090 add one way and return trip request features
  .env.example
  logs/all.log.14-04-2020
  logs/error.log.14-04-2020
  package.json
  server/controllers/tripController.js
  server/helpers/loggerHandle.js
  server/helpers/validateSchema.js
  server/middlewares/authorization.js
  server/middlewares/validators/tripValidate.js
  server/migrations/20200413134630-create-users.js
  server/migrations/20200413134641-create-trips.js
  server/migrations/20200413134708-create-triprequest.js
  server/migrations/20200413134728-create-user-management.js
  server/migrations/20200413134804-create-cities.js
  server/models/cities.js
  server/models/triprequest.js
  server/models/trips.js
  server/models/userManagement.js
  server/models/users.js
  server/routes/api/apiRoutes.js
  server/routes/api/trips/tripRoutes.js
  server/routes/api/users/userRoutes.js
  server/seeders/20200413135347-demo-user.js
  server/seeders/20200413135408-all-cities.js
  server/seeders/20200413135435-demo-management.js
  server/services/cityService.js
  server/services/templates/TripsErrorTemplate.js
  server/services/tripReqService.js
  server/services/tripServices.js
  server/services/userManagementService.js
  server/services/userService.js
  server/swagger/trip.swagger.js
  server/swagger/viewCities.swagger.js
  server/tests/app.test.js
  server/tests/auth.test.js
  server/tests/cities.test.js
  server/tests/fixtures/signupData.js
  server/tests/fixtures/tripData.js
  server/tests/signup.test.js
  server/tests/trips.test.js
Labels: Ready For Merge, enhancement

#17 #171784089 Edit User Profile Information
  .env.example
  .gitignore
  logs/all.log
  logs/all.log.14-04-2020
  logs/all.log.28-03-2020
  logs/error.log
  logs/error.log.14-04-2020
  logs/error.log.28-03-2020
  server/controllers/usercontroller.js
  server/helpers/profileFilter.js
  server/helpers/validateSchema.js
  server/middlewares/validators/validate.js
  server/middlewares/verifications/verifyUser.js
  server/migrations/20200331142748-create-users.js
  server/migrations/20200408200151-create-photos.js
  server/models/photos.js
  server/models/users.js
  server/routes/api/users/featuresRoute.js
  server/services/photoService.js
  server/swagger/profile-update.swagger.js
  server/tests/fixtures/profle.testData.js
  server/tests/update-profile.test.js
  server/tests/user.signin.test.js
Labels: Ready For Merge

#20 #171784096 add edit open trip request feature
  server/controllers/tripController.js
  server/helpers/validateSchema.js
  server/middlewares/validators/tripValidate.js
  server/middlewares/verifications/tripVerification.js
  server/models/triprequest.js
  server/models/users.js
  server/routes/api/trips/tripRoutes.js
  server/seeders/20200415153034-demo-closed-trip.js
  server/seeders/20200415153044-demo-closed-trip-request.js
  server/services/templates/TripsErrorTemplate.js
  server/services/tripReqService.js
  server/services/tripServices.js
  server/swagger/updateOpenTrip.swagger.js
  server/tests/fixtures/tripData.js
  server/tests/fixtures/updateOpenTripData.js
  server/tests/updateOpenTrip.test.js
Labels: Ready For Merge, Ready For Review

#15 #171784085 delivers login with social Media
  .env.example
  logs/all.log.15-04-2020
  logs/all.log.16-04-2020
  logs/error.log.15-04-2020
  logs/error.log.16-04-2020
  package.json
  server/app.js
  server/config/passport.js
  server/controllers/usercontroller.js
  server/helpers/profiler.js
  server/helpers/validateSchema.js
  server/migrations/20200331142748-create-users.js
  server/models/users.js
  server/routes/api/users/userRoutes.js
  server/tests/api/auth.signin.test.js
  server/tests/socialOauth.test.js
Labels: Ready For Merge, enhancement

#23 #171784093 add view trip requests feature
  .gitignore
  logs/all.log.15-04-2020
  logs/all.log.16-04-2020
  logs/error.log.15-04-2020
  logs/error.log.16-04-2020
  package.json
  server/controllers/tripController.js
  server/controllers/usercontroller.js
  server/helpers/paginationHelper.js
  server/helpers/validateSchema.js
  server/middlewares/authorization.js
  server/middlewares/roleAuthorisation.js
  server/middlewares/validators/tripValidate.js
  server/middlewares/verifications/tripVerification.js
  server/migrations/20200410175455-create-role.js
  server/models/Role.js
  server/routes/api/roles/Router.js
  server/routes/api/trips/tripRoutes.js
  server/routes/api/users/userRoutes.js
  server/seeders/20200413135347-demo-user.js
  server/seeders/20200415153034-demo-closed-trip.js
  server/seeders/20200415153044-demo-closed-trip-request.js
  server/services/templates/TripsErrorTemplate.js
  server/services/tripReqService.js
  server/swagger/updateOpenTrip.swagger.js
  server/swagger/viewAllAssigned.swagger.js
  server/swagger/viewAllTrips.swagger.js
  server/swagger/viewCities.swagger.js
  server/swagger/viewSpecific.swagger.js
  server/tests/api/auth.signin.test.js
  server/tests/api/cities.read.test.js
  server/tests/api/roles.create.test.js
  server/tests/api/roles.delete.test.js
  server/tests/api/roles.read.test.js
  server/tests/api/roles.readOne.test.js
  server/tests/api/roles.update.test.js
  server/tests/api/socialOauth.test.js
  server/tests/api/trips.create.auth.test.js
  server/tests/api/trips.create.test.js
  server/tests/api/trips.read.test.js
  server/tests/api/trips.updateOpen.test.js
  server/tests/api/users.read.test.js
  server/tests/api/users.role.update.test.js
  server/tests/data/auth.tokens.sample.js
  server/tests/fixtures/token.testData.js
  server/tests/fixtures/tripData.js
Labels: Ready For Merge, TTL Review

#21 #171784087 Setup the API for User Sign Out
  server/controllers/usercontroller.js
  server/middlewares/validators/AuthValidator.js
  server/routes/api/users/userRoutes.js
  server/seeders/20200413135347-demo-user.js
  server/swagger/auth.logout.swagger.js
  server/tests/api/auth.logout.test.js
  server/tests/api/auth.signin.test.js
  server/tests/data/api.users.sample.js
  server/tests/data/auth.tokens.sample.js
Labels: Ready For Merge, TTL Review, enhancement
