Repository STACK-UP-3/warriorz-backend, pull requests merged in 2020-06, with the labels that each got.

#31 #173093217 add Cross-origin resource sharing configuration
  package.json
  server/app.js
  server/migrations/20200413134630-create-users.js
Labels: Ready For Review, TTL Review

#32 #173229204 Set access token (JWT) to expire in one week
  server/controllers/socialOauth.js
  server/controllers/tripController.js
  server/controllers/usercontroller.js
  server/helpers/paginationHelper.js
  server/helpers/resetEncode.js
  server/middlewares/verifications/tripVerification.js
Labels: Ready For Review, TTL Review, bug

#34 #173413299 Fix issue with Sequelize seeders creating duplicate data
  server/config/config.js
Labels: Ready For Review, bug

#35 Updates The Profile A.P.I response Payload
  .gitignore
  package-lock.json
  server/controllers/socialOauth.js
  server/controllers/usercontroller.js
  server/middlewares/validators/validate.js
  server/routes/api/users/userRoutes.js
Labels: Ready For Merge
