Repository STACK-UP-3/warriorz-backend, pull requests merged in 2020-03, with the labels that each got.

#1 #171784074 Configure ESLint
  .eslintrc.json
  .gitignore
  .prettierrc
  package-lock.json
  package.json
Labels: Ready For Review

#3 #171784075 adding hound automated code review
  .hound.yml
  README.md
  package-lock.json
Labels: Ready For Review

#7 #171784073 Setup Sequelize
  .env
  .env.example
  .gitignore
  .sequelizerc
  package.json
  server/config/config.js
  server/models/index.js
Labels: Ready For Merge, Ready For Review

#10 #171784076 : setup travis ci & unit test
  .env.example
  .gitignore
  .travis.yml
  README.md
  package.json
  server/tests/setup.js
Labels: Ready For Merge

#4 #171784080 Integrate Coveralls code coverage service
  .gitignore
  README.md
  package.json
Labels: Ready For Review

#11 #171912807 deliver winston setup
  .babelrc
  .gitignore
  logger.js
  logs/all.log
  logs/error.log
  package.json
Labels: Ready For Merge
